name: WindowsBinaries

on: # Workflow triggers on both when a commit is pushed, or when a pull request is made.
    push:
        branches: 
            - dev
    pull_request:
        branches:
            - dev
    
    workflow_dispatch: # Run workflow manually from the actions tab.
    workflow_call: #For release builds
        inputs:
            buildFlags:
                required: false
                type: string


jobs:
    Windows:
        runs-on: windows-latest
        permissions: write-all

        steps:
            - name: Fetch latest commit
              uses: actions/checkout@v6.0.2
              with:
                submodules: true
            
            - name: Setup Haxe
              uses: krdlab/setup-haxe@v2.0.2
              with: 
                haxe-version: 4.3.7
            
            - name: Get cache
              uses: actions/cache@v4
              with:
                key: windows-cache
                path: |
                  .haxelib/
                  export/release/windows/haxe/
                  export/release/windows/obj/

            - name: Install/Update libs
              run: |
                haxelib setup C:/haxelib
                haxelib install hxcpp > nul --quiet
                haxelib git hxpkg https://github.com/ADA-Funni/hxpkg add-hmm-compatibility --quiet
                haxelib run hxpkg to-hmm
                
                cargo install --git https://github.com/ninjamuffin99/hmm-rs hmm-rs
                hmm-rs clean
                hmm-rs install

                haxelib fixrepo

                haxelib install hmm
                haxelib remove grig.audio
                haxelib run hmm reinstall grig.audio

                haxelib fixrepo
            
            - name: Fix Lime
              run: |
                haxelib run lime rebuild cpp
            
            - name: Compile build
              run: haxelib run lime build windows -D ${{inputs.buildFlags}}
            
            - name: Publish artifact
              uses: actions/upload-artifact@v7.0.0
              with:
                name: NightmareVision (Windows)
                path: export/release/windows/bin

            - name: Clear cache
              run: |
                echo "Clearing windows cache..."
                set +e
                gh cache delete windows-cache
                echo "Windows cache cleared!"
              env:
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                GH_REPO: ${{ github.repository }}
                BRANCH: dev

            - name: Save new cache
              uses: actions/cache@v4
              with:
                  key: windows-cache
                  path: |
                    .haxelib/
                    export/release/windows/haxe/
                    export/release/windows/obj/